# Generated by Django 4.1.3 on 2022-12-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobDescription', models.TextField(max_length=10000)),
                ('resumes', models.FileField(blank=True, null=True, upload_to='resumes/')),
            ],
        ),
    ]
